version: "2"

services:
    nginx:
        container_name: nginx
        build: ./nginx
        links:
            - app1:app1
            - app2:app2
            - app3:app3
        ports:
            - 80:80
            - 443:443
        volumes: 
            - /data/nginx:/var/log/nginx
    app1:
        container_name: app1
        build: .
        env_file: .env
        ports:
            - 3000
        links:
            - mongodb:db
    app2:
        container_name: app2
        build: .
        env_file: .env
        ports:
            - 3000
        links:
            - mongodb:db
    app3:
        container_name: app3
        build: .
        env_file: .env
        ports:
            - 3000
        links:
            - mongodb:db
    mongodb:
        container_name: mongodb
        image: mongo:3.4
        ports:
            - 27017
        volumes: 
            - /data/mongo:/data/db
