POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "웹시스템설계",
    "major": "소프트웨어학과",
    "courseNumber": "F038",
    "credit": "4",
    "time": "5",
    "professor": "오상윤",
    "lectureTime": "화C,수B,금C",
    "lectureRoom": "팔309,팔328",
    "isCyber": "false",
    "seats": "30"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "인간과 두뇌의 신비",
    "major": "교양",
    "courseNumber": "X391",
    "credit": "3",
    "time": "3",
    "professor": "김세나",
    "lectureTime": "수D,금D",
    "lectureRoom": "성105",
    "isCyber": "false",
    "seats": "42"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "수학이란 무엇인가",
    "major": "교양",
    "courseNumber": "X004",
    "credit": "3",
    "time": "3",
    "professor": "전영목",
    "lectureTime": "월B,목B",
    "lectureRoom": "원251",
    "isCyber": "false",
    "seats": "32"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "컴퓨터 네트워크",
    "major": "소프트웨어학과",
    "courseNumber": "F022",
    "credit": "3",
    "time": "3",
    "professor": "노병희",
    "lectureTime": "화B,목A",
    "lectureRoom": "팔309",
    "isCyber": "false",
    "seats": "22"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "UX디자인",
    "major": "미디어학과",
    "courseNumber": "M024",
    "credit": "3",
    "time": "3",
    "professor": "이주엽",
    "lectureTime": "화D,목C",
    "lectureRoom": "산421",
    "isCyber": "false",
    "seats": "51"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "Algorithm",
    "major": "미디어학과",
    "courseNumber": "M024",
    "credit": "3",
    "time": "3",
    "professor": "Yenewondim Sinshaw",
    "lectureTime": "월C,수C",
    "lectureRoom": "팔325",
    "isCyber": "false",
    "seats": "21"
}

###

POST http://localhost:3000/api/subject/create HTTP/1.1
content-type: application/json

{
    "name": "캡스톤디자인",
    "major": "전자학과",
    "courseNumber": "M014",
    "credit": "3",
    "time": "3",
    "professor": "Yenewondim Sinshaw",
    "lectureTime": "화C,금C",
    "lectureRoom": "팔315",
    "isCyber": "false",
    "seats": "21"
}